-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 20:29:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema systemcars_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema systemcars_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemcars_db` DEFAULT CHARACTER SET utf8 ;
USE `systemcars_db` ;

-- -----------------------------------------------------
-- Table `systemcars_db`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemcars_db`.`brands` (
  `id` INT NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `systemcars_db`.`models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemcars_db`.`models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_models_brands_idx` (`brands_id` ASC) ,
  CONSTRAINT `fk_models_brands`
    FOREIGN KEY (`brands_id`)
    REFERENCES `systemcars_db`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `systemcars_db`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemcars_db`.`vehicles` (
  `id` INT NOT NULL,
  `year_manufacture` VARCHAR(4) NOT NULL,
  `color_car` VARCHAR(32) NOT NULL,
  `mileage` DOUBLE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `price` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL,
  `brands_id` INT NOT NULL,
  `models_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicles_brands1_idx` (`brands_id` ASC) ,
  INDEX `fk_vehicles_models1_idx` (`models_id` ASC) ,
  CONSTRAINT `fk_vehicles_brands1`
    FOREIGN KEY (`brands_id`)
    REFERENCES `systemcars_db`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicles_models1`
    FOREIGN KEY (`models_id`)
    REFERENCES `systemcars_db`.`models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
